<?xml version="1.0" ?> 

<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

  transform file for source code statistics generated by the XML export feature of the Source Code Counter application.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->

<!DOCTYPE xsl:stylesheet [ 
	<!ENTITY nbsp "&#160;"> 
]> 
 
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">

<!-- create a map of file ids: used later to detect files that appear more than once -->
<xsl:key match="/statistics/file" use="@id" name="file-ids"/>

<xsl:output method="html" doctype-system="http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd" 
  doctype-public="-//W3C//DTD HTML 4.01//EN" indent="yes" />

<xsl:template match="/statistics">

<html>

<head>

<title>Statistics Result - <xsl:value-of select="@version"/></title>

<style type="text/css">
		.content-header {
			color: #000000;
			font-size: 24pt;
			font-weight: bold;
		}
	.detail-item { 
		color: #000090;
	}
	.detail-header { 
		font-family: Helvetica;
		font-size: 12pt;
		font-weight: bold;
		text-align: center;
		color: #000040;
		background-color: #A8B4D8;
	}
	.detail-total { 
		font-weight: bold;
		color: #002020;
		background-color: #90B498;
	}
	.summary-title {
		color: #900000;
		font-size: 14pt;
		font-weight: bold;
	}
	.summary-info {
		font-size: 12pt;
		font-weight: bold;
	}
    .summary-total-line {
        background-color: #7F0055;
    }
    .summary-total-code {
        background-color: #FF8000;
    }
    .summary-total-comment {
        background-color: #008000;
    }
    .summary-total-mixed {
        background-color: #008090;
    } 
    .summary-total-blank {
        background-color: #80FFFF;
    }    
</style>

</head>

<body>

  <TABLE NOSAVE="" BORDER="0" CELLSPACING="0" CELLPADDING="0" WIDTH="100%">
    <TBODY><TR NOSAVE="">
      <TD COLSPAN="2" ROWSPAN="2" NOSAVE="" class="content-header"><B>Statistics Result</B></TD>
      <TD ALIGN="RIGHT">Genrated by <B><i><xsl:value-of select="@product"/>&nbsp;v<xsl:value-of select="@version"/></i></B><br/><B><xsl:value-of select="@date"/></B></TD>
	</TR></TBODY>
  </TABLE><hr/>
  
  <TABLE border="0" WIDTH="100%">
    <TR><TD>
      <TABLE border="0">
        <TR><TD class="summary-title">Summary:&nbsp;&nbsp;</TD><TD class="summary-info">Totally <xsl:value-of select="count(file)"/> files</TD></TR>
      </TABLE>
    </TD></TR>
			
	<TR><TD>
      <TABLE BORDER="1" CELLSPACING="0" COLS="3" WIDTH="100%">
		<TR CLASS="detail-header">
		  <TD WIDTH="20%">Type</TD>
		  <TD WIDTH="10%">Count</TD>
		  <TD WIDTH="70%">Percentage(%)</TD>
		</TR>
        <xsl:variable name="total_lines" select="sum(file/lines-total)"/>
		<TR CLASS="detail-total">
			<TD>Total Lines:</TD>
			<TD ALIGN="RIGHT"><xsl:value-of select="$total_lines"/></TD>
			<TD ALIGN="RIGHT">		
				<TABLE border="0" width="100%" CLASS="detail-total">
					<TR>
                        <TD WIDTH="80" ALIGN="RIGHT">100%</TD>
                        <TD ALIGN="LEFT"><TABLE border="0" CELLSPACING="0" CELLPADDING="0" WIDTH="100%"><TR class="summary-total-line"><TD>&nbsp;</TD></TR></TABLE></TD>
					</TR>
				</TABLE>
			</TD>
		</TR>
		<TR CLASS="detail-total">
			<TD>Total Code:</TD>
			<TD ALIGN="RIGHT"><xsl:value-of select="sum(file/lines-code)"/></TD>
			<TD ALIGN="RIGHT">		
				<TABLE border="0" width="100%" CLASS="detail-total">
					<TR>
                        <xsl:variable name="percent_code">
                            <xsl:call-template name="percent"><xsl:with-param name="val" select="sum(file/lines-code)"/><xsl:with-param name="total" select="$total_lines"/></xsl:call-template>
                        </xsl:variable>
                        <TD WIDTH="80" ALIGN="RIGHT"><xsl:value-of select="$percent_code"/></TD>
                        <TD ALIGN="LEFT"><TABLE border="0" CELLSPACING="0" CELLPADDING="0" WIDTH="{$percent_code}"><TR class="summary-total-code"><TD>&nbsp;</TD></TR></TABLE></TD>
					</TR>
				</TABLE>
			</TD>
		</TR>
		<TR CLASS="detail-total">
			<TD>Total Comment:</TD>
			<TD ALIGN="RIGHT"><xsl:value-of select="sum(file/lines-comments)"/></TD>
			<TD ALIGN="RIGHT">		
				<TABLE border="0" width="100%" CLASS="detail-total">
					<TR>
                        <xsl:variable name="percent_comment">
                            <xsl:call-template name="percent"><xsl:with-param name="val" select="sum(file/lines-comments)"/><xsl:with-param name="total" select="$total_lines"/></xsl:call-template>
                        </xsl:variable>
                        <TD WIDTH="80" ALIGN="RIGHT"><xsl:value-of select="$percent_comment"/></TD>
                        <TD ALIGN="LEFT"><TABLE border="0" CELLSPACING="0" CELLPADDING="0" WIDTH="{$percent_comment}"><TR class="summary-total-comment"><TD>&nbsp;</TD></TR></TABLE></TD>
					</TR>
				</TABLE>
			</TD>
		</TR>  
		<TR CLASS="detail-total">
			<TD>Total Mixed:</TD>
			<TD ALIGN="RIGHT"><xsl:value-of select="sum(file/lines-mixed)"/></TD>
			<TD ALIGN="RIGHT">		
				<TABLE border="0" width="100%" CLASS="detail-total">
					<TR>
                        <xsl:variable name="percent_mixed">
                            <xsl:call-template name="percent"><xsl:with-param name="val" select="sum(file/lines-mixed)"/><xsl:with-param name="total" select="$total_lines"/></xsl:call-template>
                        </xsl:variable>
                        <TD WIDTH="80" ALIGN="RIGHT"><xsl:value-of select="$percent_mixed"/></TD>
                        <TD ALIGN="LEFT"><TABLE border="0" CELLSPACING="0" CELLPADDING="0" WIDTH="{$percent_mixed}"><TR class="summary-total-mixed"><TD>&nbsp;</TD></TR></TABLE></TD>
					</TR>
				</TABLE>
			</TD>
		</TR>
		<TR CLASS="detail-total">
			<TD>Total Blank:</TD>
			<TD ALIGN="RIGHT"><xsl:value-of select="sum(file/lines-blank)"/></TD>
			<TD ALIGN="RIGHT">		
				<TABLE border="0" width="100%" CLASS="detail-total">
					<TR>
                        <xsl:variable name="percent_blank">
                            <xsl:call-template name="percent"><xsl:with-param name="val" select="sum(file/lines-blank)"/><xsl:with-param name="total" select="$total_lines"/></xsl:call-template>
                        </xsl:variable>
                        <TD WIDTH="80" ALIGN="RIGHT"><xsl:value-of select="$percent_blank"/></TD>
                        <TD ALIGN="LEFT"><TABLE border="0" CELLSPACING="0" CELLPADDING="0" WIDTH="{$percent_blank}"><TR class="summary-total-blank"><TD>&nbsp;</TD></TR></TABLE></TD>
					</TR>
				</TABLE>
			</TD>
		</TR>          
	  </TABLE>
	</TD></TR>
</TABLE>

<BR/><hr/>
    
<TABLE border="0" WIDTH="100%">
	<TR><TD>
		<TABLE border="0" WIDTH="100%">
			<TR><TD class="summary-title">Detailed:</TD><TD class="summary-info"></TD></TR></TABLE>
	</TD></TR>
    
	<TR><TD>
	<table border="0" width="100%">
		<tr>
			<td>
				<table border="1" cellpadding="2" cellspacing="0" class="detail-item" width="100%">
					<!-- headings -->
					<tr class="detail-header">
						<td rowspan="2">File Name</td>
						<td colspan="5">Lines</td>
						<td rowspan="2">Path</td>
					</tr>
					<tr class="detail-header">
						<td>Total</td>
						<td>Code</td>
						<td>Comment</td>
						<td>Mixed</td>
						<td>Blank</td>
					</tr>
					<xsl:for-each select="file">
						<tr>
							<td><xsl:value-of select="name"/></td>
							<td><xsl:value-of select="lines-total"/></td>
							<xsl:variable name="total" select="lines-total"/>
							<td><xsl:call-template name="num_and_percent"><xsl:with-param name="val" select="lines-code"    /><xsl:with-param name="total" select="lines-total"/></xsl:call-template></td>
							<td><xsl:call-template name="num_and_percent"><xsl:with-param name="val" select="lines-comments"/><xsl:with-param name="total" select="lines-total"/></xsl:call-template></td>
							<td><xsl:call-template name="num_and_percent"><xsl:with-param name="val" select="lines-mixed"    /><xsl:with-param name="total" select="lines-total"/></xsl:call-template></td>
							<td><xsl:call-template name="num_and_percent"><xsl:with-param name="val" select="lines-blank"   /><xsl:with-param name="total" select="lines-total"/></xsl:call-template></td>
							<td><xsl:value-of select="path"/></td>
						</tr>
					</xsl:for-each>

					<!-- summary -->
						<tr class="detail-total">
							<td>Total:</td>
							<xsl:variable name="total" select="sum(file/lines-total)"/>
							<td><xsl:value-of select="$total"/></td>
							<td><xsl:call-template name="num_and_percent"><xsl:with-param name="val" select="sum(file/lines-code)"    /><xsl:with-param name="total" select="$total"/></xsl:call-template></td>
							<td><xsl:call-template name="num_and_percent"><xsl:with-param name="val" select="sum(file/lines-comments)"/><xsl:with-param name="total" select="$total"/></xsl:call-template></td>
							<td><xsl:call-template name="num_and_percent"><xsl:with-param name="val" select="sum(file/lines-mixed)"    /><xsl:with-param name="total" select="$total"/></xsl:call-template></td>
							<td><xsl:call-template name="num_and_percent"><xsl:with-param name="val" select="sum(file/lines-blank)"   /><xsl:with-param name="total" select="$total"/></xsl:call-template></td>

							<td>&nbsp;</td>
						</tr>

				</table>
			</td>
		</tr>
	</table>
	</TD></TR>
</TABLE>
<BR/>
<HR/>
<FONT SIZE="3">Note 1: Mixed line means Code line with Comment.</FONT>
<BR/><BR/>
<TABLE NOSAVE="" BORDER="0" CELLSPACING="0" CELLPADDING="0" COLS="1" WIDTH="100%">
	<TR ALIGN="RIGHT"><TD><FONT SIZE="2">(C) <xsl:value-of select="@orgnization"/>, Since 2011. All Rights Reserved.</FONT></TD></TR>
</TABLE>

</body>
</html>

</xsl:template>

<xsl:template name="num_and_percent">
	<xsl:param name="val"/>
	<xsl:param name="total"/>
	<xsl:value-of select="$val"/>
  <xsl:choose>
    <xsl:when test="$val = 0 or $total = 0">(0%)</xsl:when>
    <xsl:when test="$val = $total">(100%)</xsl:when>
    <xsl:when test="$total > 0 and $val != $total">(<xsl:value-of select="format-number(number(100.00 * $val div $total),'#0.00')"/>%)</xsl:when>      
  </xsl:choose>
</xsl:template>

<xsl:template name="percent">
	<xsl:param name="val"/>
	<xsl:param name="total"/>
  <xsl:choose>
    <xsl:when test="$val = 0 or $total = 0">0%</xsl:when>
    <xsl:when test="$val = $total">100%</xsl:when>
    <xsl:when test="$total > 0 and $val != $total"><xsl:value-of select="format-number(number(100.00 * $val div $total),'#0.00')"/>%</xsl:when>      
  </xsl:choose>
</xsl:template>

</xsl:stylesheet>  
