#include "StdAfx.h"
#include "Export.h"
#include "ResultListCtrl.h"
#include "CFileParser.h"

CCSVExporter::CCSVExporter(CListCtrl* pListCtrl) : m_pListCtrl(pListCtrl)
{
}

BOOL CCSVExporter::DoExport(LPCTSTR lpFileName)
{
	BOOL bResult = FALSE;

	CString szText; 
	int i, j;
	TRY
	{
		CStdioFile cFile(lpFileName, CFile::modeCreate | CFile::modeWrite);
		
		szText.Empty();
		LoadHeaderString(szText);
		cFile.WriteString(szText + "\n");
		
		
		int nColCount = m_pListCtrl->GetHeaderCtrl()->GetItemCount();
		int nRowCount = m_pListCtrl->GetItemCount();
		for(i = 0; i < nRowCount; i++)
		{
			szText.Empty();
			for(j = 0; j < nColCount; j++)
			{
				szText += m_pListCtrl->GetItemText(i, j);
				if(j < (nColCount - 1))
				{
					szText += ",";
				}
			}
			szText += "\n";
			
			cFile.WriteString(szText);
		}

		//Total Statistic


		cFile.Close();
		
		bResult = TRUE;
	}
	CATCH(CFileException, e)
	{
		TCHAR szCause[255];
		CString msg;
		
		e->GetErrorMessage(szCause, 255);	   
		AfxMessageBox(szCause, MB_OK | MB_ICONEXCLAMATION);
	}
	AND_CATCH_ALL(e)
	{
		AfxMessageBox("Error writing to file!", 
			MB_OK | MB_ICONEXCLAMATION);
	}
	END_CATCH_ALL
		
	return bResult;    
}

void CCSVExporter::LoadHeaderString(CString& str)
{
	CHeaderCtrl* pHeaderCtrl = m_pListCtrl->GetHeaderCtrl();
	int nColCount = pHeaderCtrl->GetItemCount();

	TCHAR lpBuffer[256];

	HDITEM hdi;
	hdi.mask = HDI_TEXT;
	hdi.pszText = lpBuffer;
	hdi.cchTextMax = 256;

	for(int i = 0; i < nColCount; i++)
	{
		pHeaderCtrl->GetItem(i, &hdi);
		str += hdi.pszText;
		if(i < (nColCount - 1))
		{
			str += ",";
		}
	}
}



CXLSExporter::CXLSExporter(CResultListCtrl* pListCtrl) : m_pListCtrl(pListCtrl)
{

}

BOOL CXLSExporter::DoExport(LPCTSTR lpFileName)
{
	BOOL bResult = FALSE;
	
	CDatabase database;
	//Excel driver
	CString sDriver = "MICROSOFT EXCEL DRIVER (*.XLS)";
	CString sSql;
	
	TRY
	{
		//Specifies an ODBC connect string
		sSql.Format("DRIVER={%s};DSN='';FIRSTROWHASNAMES=1;READONLY=FALSE;CREATE_DB=\"%s\";DBQ=%s",
			sDriver, lpFileName, lpFileName);
		
		//Create Excel database
		if( database.OpenEx(sSql, CDatabase::noOdbcDialog) )
		{
			m_pListCtrl->ExportAsExcel(database);
		}      
		
		//Close Database
		database.Close();

		bResult = TRUE;
	}
	CATCH_ALL(e)
	{
		TCHAR szCause[4096];
		CString msg;
		
		e->GetErrorMessage(szCause, 4096);	   
		AfxMessageBox(szCause, MB_OK | MB_ICONEXCLAMATION);
	}
	END_CATCH_ALL
	
	return bResult;
}

CXMLExporter::CXMLExporter(CResultListCtrl* pListCtrl) : m_pListCtrl(pListCtrl)
{
}

BOOL CXMLExporter::DoExport(LPCTSTR lpFileName)
{
	CString s;
    BOOL bResult = FALSE;

    TRY
    {
        CStdioFile cFile(lpFileName, CFile::modeCreate | CFile::modeWrite);

        //Get the app's path
		CString sPath;
		GetModuleFileName(NULL, sPath.GetBufferSetLength(MAX_PATH + 1), MAX_PATH);
		sPath.ReleaseBuffer();
		int nPos = sPath.ReverseFind(_T('\\'));
		sPath = sPath.Left(nPos);

		CString sXSLFileName = sPath + "\\Reports\\default.xsl";

		CString sXSLT;
		sXSLT.Format("<?xml-stylesheet type=\"text/xsl\" href=\"%s\"?>\n", sXSLFileName);
        
        
        // the header
        s.Format(
            // header
            "<?xml version=\"1.0\"?>\n"
            "\n"
            "<!--\n"
            "\n"
            " Project statistics generated by Project Line Counter\n"
            "\n"
            "\tlines-total:     count of all lines in the file\n"
            "\tlines-code:      count of lines that only have code\n"
            "\tlines-comments:  count of lines that only have comments\n"
            "\tlines-both:      count of lines that have both code and comments\n"
            "\tlines-blank:     count of lines without code or comments\n"
            "\tlines-not-blank: same as (lines-total - lines-blank) and (lines-code + lines-comments + lines-both)\n"
            "\n"
            "-->\n\n"       

            // style sheet
            "%s"

            // root
            "<statistics licence=\"%s\" date=\"%s\" plc_ver=\"%d.%02d\">\n",
            sXSLT, "Unregistered",
            CTime::GetCurrentTime().Format("%A, %B %d, %Y"),
            VERSION_MJR, VERSION_MIN);
        cFile.WriteString(s);

		int nRowCount = m_pListCtrl->GetItemCount();
		for(int i = 0; i < nRowCount; i++)
		{
			CFileInfo* pFileInfo = (CFileInfo*)m_pListCtrl->GetItemData(i);
			s.Format(
				"\t\t<file id=\"%s\">\n"
				"\t\t\t<path>%s</path>\n"
				"\t\t\t<name>%s</name>\n"
				"\t\t\t<ext>%s</ext>\n"
				"\t\t\t<lines-total>%d</lines-total>\n"
				"\t\t\t<lines-code>%d</lines-code>\n"
				"\t\t\t<lines-comments>%d</lines-comments>\n"
				"\t\t\t<lines-both>%d</lines-both>\n"
				"\t\t\t<lines-blank>%d</lines-blank>\n"
				"\t\t\t<lines-not-blank>%d</lines-not-blank>\n"
				"\t\t</file>\n",
				pFileInfo->m_sFullFileName,
				pFileInfo->m_sFilePath,
				pFileInfo->m_sFileName,
				pFileInfo->m_sFileExt,
				pFileInfo->m_nTotalLines,
				pFileInfo->m_nCodeLines,
				pFileInfo->m_nCommentLines,
				pFileInfo->GetMixedLines(),
				pFileInfo->m_nBlankLines,
				pFileInfo->m_nTotalLines - pFileInfo->m_nBlankLines);
			
			cFile.WriteString(s);
		}
		cFile.WriteString("</statistics>\n");
		cFile.Close();
		bResult = TRUE;
    }
	CATCH_ALL(e)
	{
		TCHAR szCause[4096];
		CString msg;
		
		e->GetErrorMessage(szCause, 4096);	   
		AfxMessageBox(szCause, MB_OK | MB_ICONEXCLAMATION);
	}
	END_CATCH_ALL
		
	return bResult;    
}


CHTMLExporter::CHTMLExporter(CResultListCtrl* pListCtrl) : m_pListCtrl(pListCtrl)
{
}

BOOL CHTMLExporter::DoExport(LPCTSTR lpFileName)
{
	CString s;
    BOOL bResult = FALSE;
	
    TRY
    {
        CStdioFile cFile(lpFileName, CFile::modeCreate | CFile::modeWrite);     
        
        // the header: title
		FormatHtmlHeader(s, "Statistics Result", SZ_VERSION_NAME);
        cFile.WriteString(s);
		
		//the content header
		FormatContentHeader(s, "Statistics Result", "Source Code Counter Tool");
		cFile.WriteString(s);

		//Summary Header
		FormatSummuryHeader(s, "Summary");
		cFile.WriteString(s);

		//Summary info
		//Code
		s.Format(
			"<TR><TD>%s</TD><TD ALIGN=\"RIGHT\">%d</TD>\n"
			"\t<TD>"
			"\t\t<TABLE BORDER=0 CELLSPACING=\"0\" CELLPADDING=\"0\" WIDTH=\"%d%%\"><TR BGCOLOR=\"#1A87D5\"><TD>%d%%&nbsp;</TD></TR></TABLE>"
			"\t</TD>"
			"</TR>",
			"Code", 1234, 60, 60
		);
		cFile.WriteString(s);

		//Comment
		s.Format(
			"<TR BGCOLOR=%s><TD>%s</TD><TD ALIGN=\"RIGHT\">%d</TD>\n"
			"\t<TD>"
			"\t\t<TABLE BORDER=0 CELLSPACING=\"0\" CELLPADDING=\"0\" WIDTH=\"%d%%\"><TR BGCOLOR=\"#1A87D5\"><TD>%d%%&nbsp;</TD></TR></TABLE>"
			"\t</TD>"
			"</TR>",
			GetHtmlColorStr(), "Comment", 185, 28, 28
			);
		cFile.WriteString(s);

		//Summary tail
		FormatSummuryTail(s);
		cFile.WriteString(s);

		//Detail header
		FormatDetailHeader(s, "Detailed Information");
		cFile.WriteString(s);

		//Detail Info
		int nRowCount = m_pListCtrl->GetItemCount();
		for(int i = 0; i < nRowCount; i++)
		{
			CFileInfo* pFileInfo = (CFileInfo*)m_pListCtrl->GetItemData(i);
			
			s.Format(
				"<TR>\n<TD>%s</TD>\n<TD>%d</TD>\n<TD>%d(%s)</TD>\n<TD>%d(%s)</TD>\n"
				"<TD>%d(%s)</TD>\n<TD>%d(%s)</TD>\n<TD>%s</TD>\n</TR>\n",
				pFileInfo->m_sFileName, pFileInfo->m_nTotalLines, pFileInfo->m_nCodeLines,
				CommonUtils::GetPercentStr(pFileInfo->m_nCodeLines, pFileInfo->m_nTotalLines),
				pFileInfo->m_nCommentLines, CommonUtils::GetPercentStr(pFileInfo->m_nCommentLines, pFileInfo->m_nTotalLines),
				pFileInfo->GetMixedLines(), CommonUtils::GetPercentStr(pFileInfo->GetMixedLines(), pFileInfo->m_nTotalLines),
				pFileInfo->m_nBlankLines, CommonUtils::GetPercentStr(pFileInfo->m_nBlankLines, pFileInfo->m_nTotalLines),
				pFileInfo->m_sFilePath
				);
			cFile.WriteString(s);
		}

		//Detailed Table tail
		FormatDetailTail(s);
		cFile.WriteString(s);

		//Content Tail
		FormatHtmlTail(s, "e2usoft");
		cFile.WriteString(s);

		cFile.Close();
		bResult = TRUE;
    }
	CATCH_ALL(e)
	{
		TCHAR szCause[4096];
		CString msg;
		
		e->GetErrorMessage(szCause, 4096);	   
		AfxMessageBox(szCause, MB_OK | MB_ICONEXCLAMATION);
	}
	END_CATCH_ALL
		
	return bResult;
}

CString CHTMLExporter::GetHtmlColorStr(COLORREF cr)
{
	CString str;
	str.Format("#%02X%02X%02X", GetRValue(cr), GetGValue(cr), GetBValue(cr));
	return str;
}


void CHTMLExporter::FormatHtmlHeader(CString& s, LPCTSTR lpTitle, LPCTSTR lpVersionInfo)
{
	// the header
	s.Format(
		"<HTML>\n"
		"\t<HEAD>\n"
		"\t\t<META HTTP-EQUIV=\"CONTENT-TYPE\" CONTENT=\"TEXT/HTML; CHARSET=UTF-8\" />\n"
		"\t\t<TITLE>%s - %s</TITLE>\n"
		"\t<style type=\"text/css\">\n"
		"\t\t.content-header {\n"
		"\t\t\tcolor: #000000;\n"
		"\t\t\tfont-size: 24pt;\n"
		"\t\t\tfont-weight: bold;\n"
		"\t\t}\n"
		"\t\t.filestats { \n"
		"\t\t\tcolor: #000090;\n"
		"\t\t}\n"
		"\t\t.filestats-heading { \n"
		"\t\t\tfont-family: Helvetica;\n"
		"\t\t\tfont-size: 12pt;\n"
		"\t\t\tfont-weight: bold;\n"
		"\t\t\ttext-align: center;\n"
		"\t\t\tcolor: #000040;\n"
		"\t\t\tbackground-color: #A8B4D8;\n"
		"\t\t}\n"
		"\t\t.filestats-total { \n"
		"\t\t\tfont-weight: bold;\n"
		"\t\t\tcolor: #002020;\n"
		"\t\t\tbackground-color: #90B498;\n"
		"\t\t}\n"
		"\t\t.repeated-file { \n"
		"\t\t\tfont-style: italic; \n"
		"\t\t\tcolor: #000060;\n"
		"\t\t}\n"
		"\t\t.project-title {\n"
		"\t\t\tcolor: #900000;\n"
		"\t\t\tfont-size: 14pt;\n"
		"\t\t\tfont-weight: bold;\n"
		"\t\t}\n"
		"\t\t.project-name {\n"
		"\t\t\tfont-size: 12pt;\n"
		"\t\t\tfont-weight: bold;\n"
		"\t\t}\n"
		"\t</style>\n"
		"\t</HEAD>\n"
		"\n"
		,
		lpTitle, lpVersionInfo
		);
}

void CHTMLExporter::FormatHtmlTail(CString& s, LPCTSTR lpCompany)
{
	s.Format(
		"\t\t<TABLE NOSAVE=\"\" BORDER=\"0\" CELLSPACING=\"0\" CELLPADDING=\"0\" COLS=\"1\" WIDTH=100%%>\n"
		"\t\t\t<TR><TD><HR></TD></TR>\n"
		"\t\t\t<TR ALIGN=RIGHT><TD><FONT SIZE=2>(C) %s, Since 2011. All Rights Reserved.</FONT></TD></TR>\n"
		"\t\t</TABLE>\n\n"
		"\t</BODY>\n"
		"</HTML>\n",
		lpCompany);
}

void CHTMLExporter::FormatContentHeader(CString& s, LPCTSTR lpContentHeader, LPCTSTR lpProduct)
{
	s.Format(
		"<BODY>\n"
		"<TABLE NOSAVE=\"\"  BORDER=\"0\" CELLSPACING=\"0\" CELLPADDING=\"0\" WIDTH=\"100%%\"><TBODY><TR NOSAVE=\"\">\n"
		"\t<TD COLSPAN=\"2\" ROWSPAN=\"2\" NOSAVE=\"\" CLASS=content-header><B>%s</B></FONT></TD>\n"
		"\t<TD ALIGN=\"RIGHT\">Genrated by <i>%s %s</i><BR>%s</TD>\n"
		"</TR></TBODY>\n"
		"</TABLE>\n"
		"<HR>\n"
		,
		lpContentHeader, lpProduct, SZ_VERSION_NAME,
		CTime::GetCurrentTime().Format("%A, %B %d, %Y")
		);
}

void CHTMLExporter::FormatSummuryHeader(CString& s, LPCTSTR lpSummuryTitle)
{
	s.Format(
		"<TABLE border=\"0\" WIDTH=100%%>\n"
		"\t<TR><TD>\n"
		"\t\t<TABLE border=\"0\" WIDTH=100%%>\n"
		"\t\t\t<TR><TD class=\"project-title\">%s</TD><TD class=\"project-name\"></TD></TR></TABLE>\n"
		"\t</TD></TR>\n"
		"\t<TR><TD>\n"
		"\t\t<TABLE BORDER=\"1\" CELLSPACING=\"0\" COLS=\"3\" WIDTH=100%%>\n"
		"\t\t\t<TR BGCOLOR=\"#E5E5E5\">"
		"<TH ALIGN=\"LEFT\" WIDTH=\"30%%\">TYPE</TH>"
		"<TH WIDTH=\"20%%\">LINES</TH>"
		"<TH>PERCENTAGE(%%)</TH>"
		"\t\t\t</TR>\n"
		,
		lpSummuryTitle);
}

void CHTMLExporter::FormatSummuryTail(CString& s)
{
	s.Format(
		"\t\t</TABLE>\n"
		"\t</TD></TR>\n"
		"</TABLE>\n"
		"<BR /><HR>\n");
}

void CHTMLExporter::FormatDetailHeader(CString& s, LPCTSTR lpTitle)
{
	s.Format(
		"<TABLE border=\"0\" WIDTH=100%%>\n"
		"\t<TR><TD>\n"
		"\t\t<TABLE border=\"0\" WIDTH=100%%>\n"
		"\t\t\t<TR><TD class=\"project-title\">%s</TD><TD class=\"project-name\"></TD></TR></TABLE>\n"
		"\t</TD></TR>\n"
		"\t<TR><TD>\t\n"
		"\t<TABLE BORDER=\"0\" WIDTH=100%%>\n"
		"\t\t<TR>\n"
		"\t\t<TD>\n"
		"\t\t<TABLE BORDER=\"1\" CELLPADDING=\"2\" CELLSPACING=\"0\" CLASS=\"filestats\" WIDTH=100%%>\n"
		"\t\t<TR CLASS=\"filestats-heading\">\n"
		"\t\t<TD ROWSPAN=\"2\">File Name</TD>\n"
		"\t\t<TD COLSPAN=\"5\">Lines</TD>\n"
		"\t\t<TD ROWSPAN=\"2\">Path</TD>\n"
		"\t\t</TR>\n\n"
		"\t\t<TR CLASS=\"filestats-heading\">\n"
		"\t\t\t<TD>Total</TD>\n"
		"\t\t\t<TD>Code<BR />Only</TD>\n"
		"\t\t\t<TD>Comment<BR />Only</TD>\n"
		"\t\t\t<TD>Code <BR />with Comments</TD>\n"
		"\t\t\t<TD>Blank</TD>\n"
		"\t\t</TR>\n"
		,
		lpTitle);
}
void CHTMLExporter::FormatDetailTail(CString& s)
{
	s.Format("</TABLE>\n</TD>\n</TR>\n</TABLE>\n<BR /><BR/>\n");
}